persistence true 
persistence_location    /mosquitto/data
log_dest file   /mosquitto/log/mosquitto.log

#Listen on the standard MQTT port
listener 1883 0.0.0.0
#Allow connections without username/password
allow_anonymous true