services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_practice
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb:latest
    container_name: influxdb_practice
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=my-org 
      - DOCKER_INFLUXDB_INIT_BUCKET=mqtt-data
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_practice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  
  bridge-app:
    build: ./bridge-app
    container_name: mqtt_bridge
    restart: unless-stopped
    depends_on:
      - mqtt-broker
      - influxdb
